### ISSUE TITLE
Error:  must have 'max' > 'min'

### ISSUE THREAD

**Issue by almogsi** [mattansb/cheatR#1]
@mattansb, did you encounter something like that when uploading docx files with tables?
![image](https://user-images.githubusercontent.com/26406947/46568589-31827500-c950-11e8-9b0d-375a320ef174.png)

**Comment by almogsi** [comment]
more specifically:

> Warning: Error in txtProgressBar: must have 'max' > 'min'
>   [No stack trace available]
> Warning: Error in txtProgressBar: must have 'max' > 'min'
>   89: <Anonymous>
> Warning: Error in txtProgressBar: must have 'max' > 'min'
>   169:

**Comment by mattansb** [comment]
This would only happen if `catch_em` failed to read _any_ of the listed files in `flist`, making `length(flist)` return `0`, which would cause the error in row 40:
````
pb <- txtProgressBar(min = 0, max = length(flist))
````

**Comment by mattansb** [comment]
This ^ should not cause an error, but instead will run and return an empty `results` struct. I expect the returned `results$bad_files$bad_read` to contain the input `flist`.

**Comment by mattansb** [comment]
Confirmed - `catch_em` now always return the result struct, even when failed to load all files.
This instance was due to the files being `.rtf` files disguised as `.doc` files.
